version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: wh_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
#     - "9001:9001"
    volumes:
      - ./mosquitto_config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_config/passwd:/mosquitto/config/passwd  
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log
